AddCSLuaFile 'autorun/casinocrash_config.lua'
AddCSLuaFile 'lib/3d2d_vgui/init.lua'
AddCSLuaFile 'lib/crash/client.lua'
AddCSLuaFile 'lib/crash/fonts.lua'
AddCSLuaFile 'lib/crash/helper.lua'
AddCSLuaFile 'lib/crash/client.lua'

include 'autorun/casinocrash_config.lua'
include 'lib/crash/server.lua'
include 'lib/crash/helper.lua'